src/apps/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path(
        '', views.PostListView.as_view(), name='posts_list'
    ),
    path(
        'authors/', views.AuthorListView.as_view(), name='authors_list'
    ),
    path(
        'tags/', views.TagListView.as_view(), name='tags_list'
    ),
    path(
        'post/<slug:slug>', views.PostDetailView.as_view(), name='post_detail'
    ),
    path(
        'author/<slug:slug>', views.PostsByAuthor.as_view(),
        name='posts_by_author'
    ),
    path(
        'tag/<slug:slug>', views.PostsByTag.as_view(), name='posts_bay_tag'
    ),

]

src/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/blog/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.utils import timezone

User = get_user_model()


class Post(models.Model):
    """
    Model for posts
    """

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    title = models.CharField(max_length=255, verbose_name='Post title')
    body = models.TextField(verbose_name='Post body')
    slug = models.SlugField(max_length=125, unique=True)
    image = models.ImageField(upload_to='%Y/%m/%d/', null=True, blank=True)
    status = models.CharField(
        max_length=15, choices=STATUS_CHOICES, default='draft'
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    published = models.DateTimeField(default=timezone.now)

    # relations
    author = models.ForeignKey(
        'Author', on_delete=models.CASCADE, related_name='posts'
    )
    tags = models.ManyToManyField('Tag', related_name='posts', blank=True)

    class Meta:
        ordering = ('-published',)

    def __str__(self):
        return self.title

    def get_rating(self):
        return self.votes.aggregate(Sum('value'))

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.slug])


class Author(models.Model):

    first_name = models.CharField(max_length=60, verbose_name='First name')
    last_name = models.CharField(max_length=120, verbose_name='Last name')
    slug = models.SlugField(max_length=165, unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_absolute_url(self):
        return reverse('blog:posts_by_author', args=[self.slug])


class Tag(models.Model):

    title = models.CharField(max_length=155)
    slug = models.SlugField(max_length=165, unique=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:posts_bay_tag', args=[self.slug])


#  Модель Votes создана на будущее, если реализовать в проекте регистрацию,
#  можно будет легко добавить возможность для пользователей оценивать посты


class Vote(models.Model):
    """
    Model for the formation of posts rating.
    Post can be up-voted or down-voted by user.
    """
    VOTE_CHOICES = (
        (1, 'Upvote!'),
        (-1, 'Downvote!')
    )

    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='votes'
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='votes'
    )
    value = models.SmallIntegerField(choices=VOTE_CHOICES)

    class Meta:
        unique_together = ['post', 'user']

src/apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    """
    Custom user model for future customization needs
    """
    pass

src/apps/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
from .models import Post, Author, Tag


class PostListView(ListView):

    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        qs = Post.objects.filter(status__exact='published')
        return qs


class PostDetailView(DetailView):

    template_name = 'blog/post_detail.html'

    def get_queryset(self):
        qs = Post.objects.filter(status__exact='published')
        return qs


class AuthorListView(ListView):

    model = Author
    template_name = 'blog/authors_list.html'


class TagListView(ListView):

    context_object_name = 'tags_list'
    model = Tag
    template_name = 'blog/tags_list.html'


class PostsByAuthor(ListView):

    template_name = 'blog/posts_by_author.html'
    context_object_name = 'posts'

    def get_queryset(self):
        author_slug = self.kwargs.get('slug')
        self.author = get_object_or_404(Author, slug=author_slug)
        qs = self.author.posts.filter(status__exact='published')
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author'] = self.author
        return context


class PostsByTag(ListView):

    template_name = 'blog/posts_by_tag.html'
    context_object_name = 'posts'

    def get_queryset(self):
        tag_slug = self.kwargs.get('slug')
        self.tag = get_object_or_404(Tag, slug=tag_slug)
        qs = self.tag.posts.filter(status__exact='published')
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag'] = self.tag
        return context

src/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            C & B
        {% endblock title %}
    </title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body style="display: flex; flex-direction: column" >
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'blog:posts_list' %}">Home</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:authors_list' %}">Authors<span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:tags_list' %}">Tags</a>
      </li>
        {% block sort_dropdown %}
        {% endblock sort_dropdown %}
    </ul>
  </div>
</nav>
{% block content %}
{% endblock content%}

{#Admin panel btn#}

{% if user.is_staff %}
<div class="admin-panel">
    <a href="/admin/" class="btn btn-primary">Admin</a>
</div>
{% endif %}

<nav style="flex: 0 0 auto; margin: 0 auto;">
    {% if paginator.num_pages > 1 %}
    <ul class="pagination">
        <li class="page-item">
            <a class="page-link"
               href="{% if page_obj.has_previous %}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}">
                Previous
            </a>
        </li>
        {% for page in paginator.page_range %}
            <li class="page-item {% if page_obj.number == page %} active {% endif %}"><a class="page-link"
                                                                                         href="?page={{ page }}">{{ page }}</a>
            </li>
        {% endfor %}
        <li class="page-item">
            <a class="page-link"
               href="{% if page_obj.has_next %}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}">
                Next
            </a>
        </li>
    </ul>
    {% endif %}
</nav>

</body>
</html>

src/templates/blog/authors_list.html
{% extends '_base.html' %}
{% block title %}
    Authors | {{ block.super }}
{% endblock title %}
{% block content %}
    {% for author in author_list %}
    <div class="card-header" style="margin-top: 10px; margin-left: 15%; margin-right: 25%">
        <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }},</a>
        <span style="margin-left: 15px">total posts created - {{ author.posts.all|length }}</span>
    </div>
    {% endfor %}
{% endblock content%}

src/templates/blog/index.html
{% extends '_base.html' %}

{% block title %} Homepage | {{ block.super }} {% endblock title %}

{% block content %}
{% for post in posts %}
    {% include 'blog/layouts/post_card.html' %}
{% endfor %}
{% endblock content %}

src/templates/blog/layouts/post_card.html
<div class="select2-container" style='
margin-left: 5%; background-color: azure; margin-right: 30%; margin-top: 10px;'>
    <div class="card-header">
        <a href="{{ post.author.get_absolute_url }}">{{ post.author.first_name }} {{ post.author.last_name }}</a>
    </div>
    <div class="card-body">
        <h5 class="card-title">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h5>
        <p class="card-text">{{ post.body | truncatewords:20 }}</p>
        <h6 class="card-text">Tags: {% for tag in post.tags.all %}
            <a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a> {% endfor %}
        </h6>
        <p class="cart-text">Published: {{ post.published }}</p>
    </div>
</div>

src/templates/blog/post_detail.html
{% extends '_base.html' %}
{% block title %}
    {{ post.title }} | {{ block.super }}
{% endblock title %}
{% block content %}
<div class="select2-container" style='
margin-left: 15%; background-color: azure; margin-right: 15%; margin-top: 10px;
'>
    <div class="card-header">
          By {{ post.author.first_name }} {{ post.author.last_name }}, published: {{ post.published }}
    </div>
    <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        {% if post.image %}
        <img src="/media/{{ post.image }}" alt="" height="320">
        {% endif %}
        <p class="card-text">{{ post.body }}</p>
        <h6 class="card-text">Tags: {% for tag in post.tags.all %}<a href="{{ tag.get_absolute_url }}">{{ tag.title }}</a> {% endfor %}</h6>
        <p class="card-text">Created: {{ post.created }}; Last updated: {{ post.updated }}</p>
    </div>
</div>
{% endblock content %}

src/templates/blog/posts_by_author.html
{% extends '_base.html' %}

{% block title %} {{ author.first_name }} | {{ block.super }} {% endblock title %}

{% block content %}
    <div>
        <h3 style="margin: 10px 0 10px 5%">All posts created by {{ author.first_name }} {{ author.last_name }}:</h3>
    </div>
    {% for post in posts %}
        {% include 'blog/layouts/post_card.html' %}
    {% endfor %}
{% endblock content %}

src/templates/blog/posts_by_tag.html
{% extends '_base.html' %}

{% block title %} {{ tag.title }} | {{ block.super }} {% endblock title %}

{% block content %}
    <div>
        <h3 style="margin: 10px 0 10px 5%">All posts with tag {{ tag.title }}:</h3>
    </div>
    {% for post in posts %}
        {% include 'blog/layouts/post_card.html' %}
    {% endfor %}
{% endblock content %}

src/templates/blog/tags_list.html
{% extends '_base.html' %}
{% block title %}
    Tags | {{ block.super }}
{% endblock title %}
{% block content %}
    {% for tag in tags_list %}
    <div class="card-header" style="margin-top: 10px; margin-left: 15%; margin-right: 35%">
        <a href="{{ tag.get_absolute_url }}">{{ tag.title }},</a>
        <span style="margin-left: 15px">total posts with this tag: {{ tag.posts.all|length }}</span>
    </div>
    {% endfor %}
{% endblock content%}